version: '3'

services:

  php-fpm:
    image: ${REGISTRY}/${PHP_FPM_CONTAINER_NAME}:${IMAGE_TAG}
    volumes:
     - .:/var/www/html

  nginx:
    image: ${REGISTRY}/${NGINX_CONTAINER_NAME}:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
    volumes:
      - .:/var/www/html

 